#!/bin/sh
##
# gpassword - change password convenience script
#
# 2020-08-28 Generations Linux <bugs@softcraft.org>
#
OLDPASS=`zenity --entry \
          --title="Change password." \
          --text="Enter your password:" \
          --entry-text "" \
          --hide-text`

if [ $? -eq 0 ] && [ -n "$OLDPASS" ]; then
  NEWPASS=`zenity --entry \
             --title="Change password." \
             --text="Enter new password:" \
             --entry-text "" \
             --hide-text`

  if [ $? -eq 0 ] && [ -n "$NEWPASS" ]; then
    CONFIRM=`zenity --entry \
               --title="Change password." \
               --text="Retype new password:" \
               --entry-text "" \
               --hide-text`

    if [ $? -eq 0 ] && [ -n "$CONFIRM" ]; then
      if [ "$NEWPASS" = "$CONFIRM" ]; then
        printf "%s\n%s\n%s\n" $OLDPASS $NEWPASS $CONFIRM |passwd >/dev/null 2>&1

        if [ $? -eq 0 ]; then
          zenity --info \
           --title="Change password." \
           --text="Password successfully changed!"
        else
          zenity --error \
           --title="Change password." \
           --text="Sorry, password is too simple."
        fi
      else
        zenity --error \
         --title="Change password." \
         --text="Sorry, passwords do not match."
      fi
    fi
  fi
fi

