#!/bin/sh
# $Id: xinitrc,v 1.0.16 2008/11/06 softcraft Exp $
###
##
# X Window System session initialization file.
#
# 2006-02-28 Generations Linux <info@softcraft.org>
##
###

XSESSION=/etc/X11/xinit/xsession
[ -r $HOME/.xsession ] && XSESSION=$HOME/.xsession
[ -x $XSESSION ] || XSESSION="sh $XSESSION"

exec $XSESSION "$@"
