#!/bin/sh
##
# X Window System session initialization file.
#
# 2006-02-28 Generations Linux <bugs@softcraft.org>
#

XSESSION=/etc/X11/xinit/xsession
[ -r $HOME/.xsession ] && XSESSION=$HOME/.xsession
[ -x $XSESSION ] || XSESSION="sh $XSESSION"

exec $XSESSION "$@"
